id: P010431
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9244
  title: འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོའི་གསུང་འབུམ་དཀར་ཆག་གི་མཆན།
  author: ''
  volumes:
    a5642064f42a44b9b6dc52327d4912f9:
      image_group_id: I1KG9502
      title: ''
      volume_number: 1
      total_pages: 392
      base_file: v001.txt
